Repository bitwyre/ui-kit, pull requests merged in 2024-02, with the labels that each got.

#2 feat(ui-kit/drawer): added drawer component
  .vscode/settings.json
  packages/ui/src/components/drawer.tsx
  packages/ui/src/components/index.ts
  packages/ui/src/components/svg/index.ts
Labels: size/L

#3 feat(ui-kit/card): create card component
  packages/ui/src/components/card.tsx
Labels: size/M

#5 chore(dx): integrate git hooks with lint-staged
  .husky/pre-commit
  package.json
  pnpm-lock.yaml
Labels: size/XL

#6 feat(component): adding component drawer and card with variants
  .vscode/settings.json
  packages/ui/src/components/card.tsx
  packages/ui/src/components/drawer.tsx
  packages/ui/src/components/index.ts
  packages/ui/src/components/svg/index.ts
Labels: size/L

#7 feat(input-components): creating input components with RHF config
  README.md
  apps/web/.eslintignore
  apps/web/app/layout.tsx
  package.json
  packages/ui/.eslintignore
  packages/ui/package.json
  packages/ui/src/components/index.ts
  packages/ui/src/components/input.tsx
  packages/ui/src/components/svg/index.ts
  packages/ui/src/types/index.d.ts
  packages/ui/tsconfig.json
  pnpm-lock.yaml
Labels: size/L

#9 feat(components/notify): create notify component
  .eslintignore
  apps/docs/.ladle/components.tsx
  apps/docs/src/components/notify.stories.tsx
  apps/web/package.json
  packages/ui/package.json
  packages/ui/src/components/drawer.tsx
  packages/ui/src/components/index.ts
  packages/ui/src/components/notify.tsx
Labels: size/M

#10 feat(input-component): adding input tsdoc and component docs
  apps/docs/package.json
  apps/docs/src/components/input.stories.tsx
  apps/web/app/page.tsx
  packages/ui/package.json
  packages/ui/src/components/input.tsx
  packages/ui/src/components/svg/index.ts
  pnpm-lock.yaml
Labels: size/XL

#11 feat(components/common): create common components
  apps/docs/src/components/common.stories.tsx
  packages/ui/src/components/common.tsx
  packages/ui/src/components/index.ts
Labels: size/L

#12 feat(button-component): create button component
  apps/docs/src/components/button.stories.tsx
  apps/docs/src/components/notify.stories.tsx
  packages/ui/src/components/button.tsx
  packages/ui/tailwind.config.ts
Labels: size/L

#13 feat(components/popover): create popover component
  apps/docs/src/components/popover.stories.tsx
  package.json
  packages/ui/package.json
  packages/ui/src/components/index.ts
  packages/ui/src/components/popover.tsx
  packages/ui/src/components/svg/index.ts
  pnpm-lock.yaml
Labels: size/L

#15 feat(dropdown-component): creating dropdown menu component with docs
  apps/docs/src/components/dropdown-menu.stories.tsx
  packages/icons/index-template.js
  packages/icons/package.json
  packages/ui/package.json
  packages/ui/src/components/dropdown-menu.tsx
  packages/ui/src/components/index.ts
  pnpm-lock.yaml
Labels: size/XL

#18 feat(aspectratio-component): creating aspect ratio component with docs usage
  apps/docs/src/components/aspect-ratio.stories.tsx
  packages/ui/package.json
  packages/ui/src/components/aspect-ratio.tsx
  packages/ui/src/components/index.ts
  pnpm-lock.yaml
Labels: size/M

#17 feat(form-component): creating form component with custom rich hook form integration
  .eslintignore
  apps/docs/package.json
  apps/docs/src/components/formfields.stories.tsx
  apps/docs/src/components/input.stories.tsx
  apps/web/.eslintignore
  apps/web/package.json
  package.json
  packages/eslint-config/.npmignore
  packages/ui/.eslintignore
  packages/ui/index.ts
  packages/ui/package.json
  packages/ui/src/components/form.tsx
  packages/ui/src/components/index.ts
  packages/ui/src/components/input.tsx
  packages/ui/src/components/label.tsx
  packages/ui/src/lib/utils.ts
  packages/ui/tsconfig.json
  pnpm-lock.yaml
  turbo.json
Labels: size/L

#16 feat(select-component): creating select component with docs usage
  apps/docs/src/components/popover.stories.tsx
  apps/docs/src/components/select.stories.tsx
  packages/ui/package.json
  packages/ui/src/components/button.tsx
  packages/ui/src/components/card.tsx
  packages/ui/src/components/common.tsx
  packages/ui/src/components/drawer.tsx
  packages/ui/src/components/form.tsx
  packages/ui/src/components/index.ts
  packages/ui/src/components/notify.tsx
  packages/ui/src/components/popover.tsx
  packages/ui/src/components/select.tsx
  packages/ui/src/lib/utils.ts
  pnpm-lock.yaml
Labels: size/L

#19 feat(example): adding example usage bitwyre ui kit with nextui component kit
  apps/docs/package.json
  apps/docs/src/components/skeleton.stories.tsx
  apps/docs/src/components/slider.stories.tsx
  apps/docs/tailwind.config.js
  packages/ui/tailwind.config.ts
  pnpm-lock.yaml
Labels: documentation, size/XL

#20 fix(rules-eslint): fix rules eslint for ban-ts-comment on uikit package
  apps/docs/src/components/select.stories.tsx
  packages/ui/.eslintrc.js
Labels: size/S

#23 feat(components/sheet): create sheet component
  .vscode/settings.json
  apps/docs/src/components/sheet.stories.tsx
  packages/ui/package.json
  packages/ui/src/components/index.ts
  packages/ui/src/components/sheet.tsx
  pnpm-lock.yaml
Labels: size/L

#21 feat(accordion-component): create accordion component with docs
  apps/docs/src/components/accordion.stories.tsx
  packages/ui/src/components/accordion.tsx
Labels: size/L

#24 feat(components/pagination): create pagination component
  apps/docs/src/components/pagination.stories.tsx
  packages/ui/index.ts
  packages/ui/package.json
  packages/ui/src/components/index.ts
  packages/ui/src/components/pagination.tsx
  packages/ui/src/hooks/index.ts
  packages/ui/src/hooks/useMediaQuery.ts
  pnpm-lock.yaml
Labels: size/L

#22 feat(popup-component): create pop up component
  apps/docs/src/components/popup.stories.tsx
  packages/ui/package.json
  packages/ui/src/components/index.ts
  packages/ui/src/components/popup.tsx
  pnpm-lock.yaml
Labels: size/L

#26 feat(components/navigation-menu): create navigation menu component
  apps/docs/src/components/navigation-menu.stories.tsx
  packages/ui/package.json
  packages/ui/src/components/index.ts
  packages/ui/src/components/navigation-menu.tsx
  pnpm-lock.yaml
Labels: size/L

#27 docs(components/drawer): create use case stories for drawer
  apps/docs/src/components/drawer.stories.tsx
  packages/ui/src/components/drawer.tsx
Labels: size/M

#29 feat(components/tabs): create tabs component
  apps/docs/src/components/tabs.stories.tsx
  packages/ui/package.json
  packages/ui/src/components/index.ts
  packages/ui/src/components/tabs.tsx
  pnpm-lock.yaml
Labels: size/L

#28 feat(cmdk-component): create cmdk component and dialog component
  apps/docs/src/components/cmdk.stories.tsx
  apps/docs/src/components/dialog.stories.tsx
  packages/ui/package.json
  packages/ui/src/components/cmdk.tsx
  packages/ui/src/components/dialog.tsx
  packages/ui/src/components/index.ts
  pnpm-lock.yaml
Labels: size/XXL

#30 fix(pagination,popup): fix popup onclose and pagination not work
  packages/ui/index.ts
  packages/ui/package.json
  packages/ui/src/components/button.tsx
  packages/ui/src/components/pagination.tsx
  packages/ui/src/components/popup.tsx
  packages/ui/src/hooks/index.ts
  packages/ui/src/hooks/useMediaQuery.ts
  pnpm-lock.yaml
Labels: size/XXL
